import { z } from "zod";
import { fullNameValidator } from "../authSchema/AuthSchema";

export const clientSchema = z.object({
  fullName: fullNameValidator,
  // clientId is auto-generated by the backend — not entered by the user
  age: z.coerce.number().min(0, "Age must be a valid number").max(150, "Age must be at most 150").optional(),
  contactNo: z.string().min(10, "Contact number is required and must be at least 10 digits.").max(20, "Contact No not more then 20character"),
  address: z.string().min(1, "Address is required."),
  // address: z.string().optional(),
  // status: z.string().min(1, "Status No is required"),
  status: z.string().optional(),
  // address: z.string().min(1, "Address No is required and should not less then 10characters"),
  // status: z.string().min(1, "Status No is required"),
  email: z.string().email(),
  // gender: z.string().min(1, "Gender No is required"),
  gender: z.string().optional(),
  // gender: z.string().min(1, "Gender No is required"),
  // profileImg: z.string().optional()
  // country: z.string().min(1, "Country is required"),
  //country: z.literal("US", { message: "Only United States is supported" }),
  // country: z.string().min(1, "Country is required"),
  state: z.string().min(1, "State must be selected"),

})
export const accountSchema = z.object({
  fullName: z.string().min(2, "Full name is required"),
  licenseNo: z.string().optional(),
  email: z.string().email("Enter valid email address"),
  address: z.string().optional(),
  // country: z.literal("US", { message: "Only United States is supported" }),
  state: z.string().min(1, "State must be selected"),
  // password: z
  //     .string()
  //     .optional()
  //     .refine(
  //         (val) => !val || val.length >= 10,
  //         { message: "Password is required and should not be less than 10 characters" }
  //     )
})
export type AccountSchemaType = z.infer<typeof accountSchema>;